@startditaa
                               fread/fwrite replacement
 fileOpen()-->+-----------+bytes+---------------+blocks+---------------+-->open()
 fileRead()-->|           |     |               |      |               |-->read()
fileWrite()-->|File Source|<--->|Buffered Stream|<---->|Filesystem Sink|-->write()
 fileSync()-->|           |     |               |      |               |-->fsync()
fileClose()-->+-----------+     +---------------+      +---------------+-->close()
@endditaa

@startditaa
                                               With Compression
 fileOpen()-->+-----------+bytes+---------------+bytes+---------------+blocks+---------------+-->open()
 fileRead()-->|           |     |               |     |               |      |               |-->read()
fileWrite()-->|File Source|<--->|Buffered Stream|<--->|LZ4 Compression|<---->|Filesystem Sink|-->write()
 fileSync()-->|           |     |               |     |               |      |               |-->fsync()
fileClose()-->+-----------+     +---------------+     +---------------+      +---------------+-->close()
@endditaa


@startditaa
                                               With Encryption
 fileOpen()-->+-----------+bytes+---------------+blocks+--------------+blocks+---------------+-->open()
 fileRead()-->|           |     |               |      |              |      |               |-->read()
fileWrite()-->|File Source|<--->|Buffered Stream|<---->|AES Encryption|<---->|Filesystem Sink|-->write()
 fileSync()-->|           |     |               |      |              |      |               |-->fsync()
fileClose()-->+-----------+     +---------------+      +--------------+      +---------------+-->close()
@endditaa


@startditaa
                                     Split a stream into multiple files.
 fileOpen()-->+-----------+bytes+---------------+blocks+----------+  +--\blocks+---------------+-->open()
 fileRead()-->|           |     |               |      |          +--+  |      |               |-->read()
fileWrite()-->|File Source|<--->|Buffered Stream|<---->|File Split|  :  :<---->|Filesystem Sink|-->write()
 fileSync()-->|           |     |               |      |          +--+  |      |               |-->fsync()
fileClose()-->+-----------+     +---------------+      +----------+  +--/      +---------------+-->close()
                                                                  Multiple
                                                                    Files
@endditaa
